{{- if .Values.psp.create -}}

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ printf "%s-psp" (include "minio.fullname" .) | quote}}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "minio.chart" . }}
    app: {{ template "minio.name" . }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim

{{- end -}}
