{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) }}
{{- if .Values.securityContext.podSecurityPolicy.enabled}}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "postgresql.fullname" . }}
spec:
{{ toYaml .Values.securityContext.podSecurityPolicy.policy | indent 2 }}
{{- end }}
{{- end }}
