{{ if or (not .Values.rabbitmq.existingErlangSecret) (not .Values.rabbitmq.existingPasswordSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if not .Values.rabbitmq.existingPasswordSecret }}{{ if .Values.rabbitmq.password }}
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
  {{ else }}
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}{{ end }}
  {{ if not .Values.rabbitmq.existingErlangSecret }}{{ if .Values.rabbitmq.erlangCookie }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.erlangCookie | b64enc | quote }}
  {{ else }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}{{ end }}
  {{ if not .Values.rabbitmq.mqtt.existingSecret }}{{ if .Values.rabbitmq.mqtt.password }}
  rabbitmq-mqtt-password: {{ .Values.rabbitmq.mqtt.password | b64enc | quote }}
  {{ else }}
  rabbitmq-mqtt-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}{{ end }}
{{ end }}
